name: Tests

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        typo3: [ ^12.4 ]
        php: [ '8.3', '8.4', '8.5' ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 10

      - name: Set up PHP Version ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2

      - name: Environment Check
        run: |
          php --version
          composer --version

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Install dependencies with typo3/cms-core:${{ matrix.typo3 }}
        run: |
          composer require --dev typo3/cms-core:${{ matrix.typo3 }} --no-progress
          git checkout composer.json
          ln -nfs .Build/vendor/typo3/cms/typo3 typo3

      - name: Lint PHP
        run: find . -name \*.php ! -path "./.Build/*" ! -path "./scripts/*" ! -path "./typo3_src/*" | parallel --gnu php -d display_errors=stderr -l {} > /dev/null \;

      - name: check code-style
        if: matrix.typo3 == '^12.4' && matrix.php == '8.4'
        run: |
          composer code-check-pipeline

      - name: Unit Tests without coverage
        if: matrix.typo3 != '^12.4' || matrix.php != '8.4' && matrix.php != 8.5
        run: composer test:unit

      - name: Unit Tests without coverage
        if: matrix.typo3 != '^12.4' || matrix.php == '8.5'
        run: composer test:unit || true

      - name: Unit Tests with coverage
        if: matrix.typo3 == '^12.4' && matrix.php == '8.4'
        run: |
          export "UNIT_XML"=.Build/vendor/typo3/testing-framework/Resources/Core/Build/UnitTests.xml
          .Build/bin/phpunit --coverage-filter Classes --coverage-clover=coverage/unittest-coverage.clover --colors -c $UNIT_XML Tests/Unit

      - name: Upload functional coverage results to Scrutinizer
        uses: sudo-bot/action-scrutinizer@latest
        if: matrix.typo3 == '^12.4' && matrix.php == '8.4'
        with:
          cli-args: "--format=php-clover functional-coverage.clover --revision=${{ github.event.pull_request.head.sha || github.sha }}"
